### ISSUE TITLE
Adding SwiftLint as an dependency with Swift Package Manager results in build errors

### ISSUE THREAD

**Issue by mikaelbartlett** [realm/SwiftLint#3073]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When adding swiftlint as a dependency with SPM it fails to build the executable. Cloning latest and checking out 0.38.2 works and the command ´swift run swiftlint´works.

##### Complete output when running SwiftLint, including the stack trace and command used

´swift run swiftlint´

First error:
´
.build/checkouts/SwiftLint/Source/SwiftLintFramework/Rules/Idiomatic/ConvenienceTypeRule.swift:101:94: error: extra argument 'length' in call
                let contents = file.stringView.substringWithByteRange(start: offset, length: length) else {
´

### Environment

Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.3.0

**Comment by heinzl** [comment]
We are experiencing the same issue when including swiftlint as an SPM dependency using the latests release `..., from: "0.38.2"`, but it works if we use `..., .branch("master")`

**Comment by borut-t** [comment]
SPM doesn't work with `0.39.2` version either. `SourceKittenFramework` throws compile errors.

**Comment by t651330** [comment]
Did anybody maybe find the last release where running the `swift run swiftLint` command succeeds? 

I would not build something rather using `master`

**Comment by dirtydanee** [comment]
Did anybody maybe find the last release where running the `swift run swiftLint` command succeeds? I would not build something rather using `master`.

**Comment by stevo-knievo** [comment]
I have the same issue as @borut-t with `0.39.2` and `master`

**Comment by lincolnAB** [comment]
I have the same issue.

**Comment by andre991** [comment]
I have the same issue. Xcode 12.1

**Comment by jpsim** [comment]
> Use of unresolved identifier 'Process'
> 'sortedKeys' is only available in iOS 11.0 or newer

These indicate to me that SwiftLint is being compiled for an iOS platform target. SwiftLint can only be built on macOS and Linux.

**Comment by edias** [comment]
what does it means @jpsim? How can we configure SwiftLint to run with SPM on Xcode12.1. I'm having the same issue with Xcode 12.1 and SwiftLint 0.41.

**Comment by jpsim** [comment]
Please open a new issue with the complete steps you’re taking to encounter the issue and I might be able to help more.

**Comment by ankitkumar130** [comment]
@jpsim are you in hurry to close issues.

**Comment by fuxlud** [comment]
When adding the SwiftLint Package Dependency, do not add the Package Products (SwiftLintFramework and swiftlint) to your targets (do not check the check boxes). Just press the "Add Package" and this should work.

**Comment by OlegEremenko991** [comment]
> When adding the SwiftLint Package Dependency, do not add the Package Products (SwiftLintFramework and swiftlint) to your targets (do not check the check boxes). Just press the "Add Package" and this should work.

The build succeeds, but SwiftLint does not check for warnings. This script in build phase does not work, how to fix it?

if which swiftlint >/dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi

**Comment by YesidMarin** [comment]
Hello, any solution for this issue? I have errors when build.

![image](https://github.com/realm/SwiftLint/assets/29234631/f3c61014-624a-46e6-83bd-78798995dbb1)

**Comment by SooHoon95** [comment]
same issue with above

**Comment by mildm8nnered** [comment]
> same issue with above

If you're seeing the same error messages as @YesidMarin , then your project is trying to build SwiftLint for iOS, which will not work.

Try following this suggestion:

https://github.com/realm/SwiftLint/issues/3073#issuecomment-934301131

**Comment by ZmicierBiesau** [comment]
In Xcode 15, try to remove Swiftlint Package from target. Then press add and where you will select libraries to what target add, select "None" and go on. This helped me.

**Comment by SooHoon95** [comment]
> In Xcode 15, try to remove Swiftlint Package from target. Then press add and where you will select libraries to what target add, select "None" and go on. This helped me.

can you add screen shot?

**Comment by ZmicierBiesau** [comment]
> > In Xcode 15, try to remove Swiftlint Package from target. Then press add and where you will select libraries to what target add, select "None" and go on. This helped me.
> 
> can you add screen shot?
![Screenshot 2023-10-20 at 12 42 47](https://github.com/realm/SwiftLint/assets/12990730/0ceb3dd6-d15a-4a2e-9d4f-4eaf871bdb6f)

**Comment by SooHoon95** [comment]
> > > In Xcode 15, try to remove Swiftlint Package from target. Then press add and where you will select libraries to what target add, select "None" and go on. This helped me.
> > 
> > 
> > can you add screen shot?
> > ![Screenshot 2023-10-20 at 12 42 47](https://github.com/realm/SwiftLint/assets/12990730/0ceb3dd6-d15a-4a2e-9d4f-4eaf871bdb6f)
> 
> P.S. In this case it still will be able to add SwiftLintPlugin in Run Build Tool Plug-ins and you need to add it. ![Screenshot 2023-10-20 at 12 48 05](https://user-images.githubusercontent.com/12990730/276892606-2721fbfc-4df1-4f23-b0ee-60c868ff3621.png)

Thanks I'll try it
