### ISSUE TITLE
illegal instruction: 4 swiftlint on Xcode 11

### ISSUE THREAD

**Issue by Igor-Palaguta** [realm/SwiftLint#2793]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

On beta 2 everything worked fine, but on Xcode 11 beta 3 swiftlint starts failing with `illegal instruction: 4 swiftlint`

```shell
SwiftLint.build/Script-77CC59392189ADCC00127275.sh: line 9: 34044 Illegal instruction: 4  swiftlint
```

After commenting opt in rules one by one found that it was because of `reduce_into` and `trailing_closure` rules

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

```
Linting 'AAAA.swift' (199/1121)
Linting 'AAAA.swift' (200/1121)
Linting 'AAAA.swift' (201/1121)
Linting 'AAAA.swift' (202/1121)
Linting 'AAAA.swift' (203/1121)
Illegal instruction: 4
```

After commenting:
```
  #- reduce_into
  #- trailing_closure
```

* SwiftLint version (run `swiftlint version` to be sure)?
0.33.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
package attached to github release
* Paste your configuration file:

```yml
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - conditional_returns_on_newline
  - discouraged_object_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - legacy_random
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - yoda_condition
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcode-select -p`)?
```shell
xcodebuild -version
Xcode 11.0
Build version 11M362v
```

**Comment by Igor-Palaguta** [comment]
<img width="1088" alt="Screenshot 2019-07-04 at 18 36 31" src="https://user-images.githubusercontent.com/800044/60680195-ab696f80-9e8a-11e9-8eb8-e3c9569e42d3.png">

**Comment by marcelofabri** [comment]
Can you provide a sample snippet that triggers the issue when linted?

**Comment by Igor-Palaguta** [comment]
It fails in rawStrings with properties inside interpolation

```swift
import XCTest

final class Class: XCTestCase {
    func testA() {
        let data = Data(#"{"status":100, "code":\#(a.code), "message": "failure"}"#.utf8)
    }
}
```

**Comment by jpsim** [comment]
Thanks for sharing steps to reproduce! I have a fix in progress here: https://github.com/jpsim/SourceKitten/pull/602

**Comment by jpsim** [comment]
Actually, digging more into this, it's a bug in SourceKit in Xcode 11. Will report back when I've filed a bug at bugs.swift.org.

**Comment by jpsim** [comment]
Filed a bug against SourceKit: https://bugs.swift.org/browse/SR-11099

**Comment by Igor-Palaguta** [comment]
Thank you!

**Comment by Igor-Palaguta** [comment]
Same issue in new rule `no_space_in_method_call` in 0.35.
<img width="1088" alt="Screenshot 2019-09-06 at 17 40 37" src="https://user-images.githubusercontent.com/800044/64441122-86cd8600-d0cd-11e9-818a-d30302f2e84f.png">

**Comment by lgaches** [comment]
Same issue with Xcode 11 Beta 7. Disabling `no_space_in_method_call` helps.

**Comment by Doxxer** [comment]
Also, disabling `reduce_into` opt-in rule helps

**Comment by HevaWu** [comment]
Xcode 11 GM with `0.34.0` works for me. 
But have the same issue with `0.35.0` 😢 
Will waiting for the new update .....

**Comment by chrisballinger** [comment]
I'm also hitting this issue on Xcode 11.1. Not sure what file it's happening on because if I lint just the last file it succeeds.

**Comment by chrisballinger** [comment]
In my case it was because of a file that ended with a `#endif` with no accompanying `#if`. I didn't see the compilation error because SwiftLint was failing before the compilation step in our build process.

**Comment by thuss** [comment]
SwiftLint 0.34.0 (as opposed to the current 0.35.0) does seem to work fine with Xcode 11.1 so for anyone looking for a short-term workaround you can install 0.34.0 with `Homebrew` as follows:

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6a748c632794a33350c415a4f330800095fdc730/Formula/swiftlint.rb
```

**Comment by jpsim** [comment]
It looks like the Swift fix landed in 5.1.1. Closing this.

**Comment by broadwaylamb** [comment]
I'm still getting this with Swift 5.1.2 (Xcode 11.2) and SwiftLint 0.36.0.

**Comment by jpsim** [comment]
@broadwaylamb thanks for sharing. Could you share steps to reproduce in a new issue please? Sounds like a new issue.

**Comment by broadwaylamb** [comment]
@jpsim sure.

I'm using SwiftLint 0.36.0, macOS 10.15.1 with Xcode 11.2 and Swift 5.1.2.

```
git clone https://github.com/broadwaylamb/OpenCombine.git swiftlint-crash
cd swiftlint-crash
git checkout 806ea79d672c58ef53a79df1e01253332e7af5c6
swiftlint
```

After linting some files I get:

```
[1]    27084 illegal hardware instruction  swiftlint
```

**Comment by jpsim** [comment]
Thanks for sharing! Turns out that even though the fix https://github.com/apple/swift/pull/27186 was included in the `swift-5.1-branch` before its version was set to 5.1.1, the fix hasn't actually made it into Xcode's Swift toolchains for 5.1.1 or 5.1.2 😞.

You can work around this by using the latest Swift 5.1 OSS toolchain:

```
git clone https://github.com/broadwaylamb/OpenCombine.git swiftlint-crash
cd swiftlint-crash
git checkout 806ea79d672c58ef53a79df1e01253332e7af5c6
TOOLCHAIN_DIR=/Library/Developer/Toolchains/swift-5.1-DEVELOPMENT-SNAPSHOT-2019-11-05-a.xctoolchain swiftlint
```

**Comment by dhritzkiv** [comment]
Looks like the desired Swift toolchain is in the current App Store version of XCode (11.3.1). Running SwiftLint no longer results in illegal instruction errors.

**Comment by bartshappee** [comment]
I'm still seeing it with 11.3.1, default toolchain
