### ISSUE TITLE
Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed zsh: illegal hardware instruction  swiftlint

### ISSUE THREAD

**Issue by InfinityCode777** [realm/SwiftLint#6475]
### New Issue Checklist

- [ x] I've Updated SwiftLint to the latest version.
- [ x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

I just upgraded to Xcode 26.2 and swiftLint to 0.63.2 (see more in environment section). The Xcode build phase script failed to execute. 

(1) I tried the method mentioned in many comments 

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

but it does not work for me, if you check the snapshot below, it shows the 

```
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
``` 

<img width="2372" height="690" alt="Image" src="https://github.com/user-attachments/assets/3db91498-0f71-4298-9493-d6f195a675ec" />

(2) [Some folks](https://github.com/realm/SwiftLint/issues/6221#issuecomment-3299086495) mentioned that they got it work on Xcode 26.0 (17A324) and I am not sure this is a Xcode specific problem. 

#### Build Phase Script
```
if [ "$CI_TEST" == true ]; then
    echo "Not local env, skip swiftLint"
    exit 0
else
    echo "Start swiftLint"
fi


if [[ "$(uname -m)" == arm64 ]]
then
    export PATH="/opt/homebrew/bin:$PATH"
fi

if which swiftlint >/dev/null; then
    swiftlint --fix && swiftlint
    # echo "swiftLint disabled"
else
    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
    exit 1
fi
```

### Environment

<img width="2676" height="816" alt="Image" src="https://github.com/user-attachments/assets/6f44582d-c229-460e-bd0a-c1ba1689b92c" />

#### .yml 
```
disabled_rules:
  - statement_position # https://realm.github.io/SwiftLint/statement_position.html
  - colon
  - nesting
  - line_length
  - identifier_name
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - function_body_length
  - type_name
  - file_length
  - type_body_length
  - function_parameter_count
  - large_tuple
  - redundant_discardable_let
  - for_where
  - unneeded_synthesized_initializer

included:
  - <MY_PROJECT>
  - <MY_PROJECT>Tests
  - <MY_PROJECT>UITests
  
excluded:
  - Packages/<MY_PROJECT>/Sources/<MY_PROJECT>/Hashids.swift

```

**Comment by AHaManz** [comment]
same error

**Comment by guruz** [comment]
I think I fixed this by removing the old Intel Rosetta homebrew and re-installing a Apple Silicon homebrew (and SwiftLint).

**Comment by SimplyDanny** [comment]
@InfinityCode777: Is the problem fixed for you as well?

**Comment by danielsunarjo-png** [comment]
Happened here after upgrading xcode to 26.x aswell,
the workaround is you can use 

`SWIFTLINT_DISABLE_SOURCEKIT=1 <command>`

but i believe it will skips some rule

**Comment by SimplyDanny** [comment]
> Happened here after upgrading xcode to 26.x aswell, the workaround is you can use
> 
> `SWIFTLINT_DISABLE_SOURCEKIT=1 <command>`
> 
> but i believe it will skips some rule

It will skip the rules that require SourceKit. There are only a few of such rules left, so that's maybe not a too serious restriction. Note that there is also the command-line flag `--disable-sourcekit` with the same effect.
